In [1]:
import numpy as np

In [2]:
filepath = "../../data/europe-seasonal.txt"
data = np.loadtxt(filepath, converters=None, skiprows=119)

In [4]:
#np.set_printoptions.func_globals

In [5]:
data.shape

(505, 6)

In [6]:
np.loadtxt(filepath, converters=None, skiprows=119)

array([[  1.50000000e+03,  -9.45000000e-01,   7.15700000e+00,
          1.74830000e+01,   8.99000000e+00,   8.16600000e+00],
       [  1.50100000e+03,  -8.50000000e-01,   7.43500000e+00,
          1.74010000e+01,   8.68700000e+00,   8.16300000e+00],
       [  1.50200000e+03,  -1.05300000e+00,   6.87200000e+00,
          1.79060000e+01,   9.07100000e+00,   8.19400000e+00],
       ..., 
       [  2.00200000e+03,   2.07000000e-01,   9.21400000e+00,
          1.89050000e+01,   9.30100000e+00,   9.50800000e+00],
       [  2.00300000e+03,  -1.10100000e+00,   8.52100000e+00,
          1.96150000e+01,   9.83800000e+00,   9.37400000e+00],
       [  2.00400000e+03,   1.87000000e-01,   8.29700000e+00,
          1.83250000e+01,   1.00730000e+01,   9.23500000e+00]])

In [1]:
filepath = "../../data/europe-seasonal.txt"
data = np.loadtxt(filepath, converters=None, skiprows=119)
print(data)

NameError: name 'np' is not defined

In [15]:
print('random value in data:', data[250, 2])

('random value in data:', 8.2959999999999994)


In [7]:
print(data[0:4, 0:10])

[[  1.50000000e+03  -9.45000000e-01   7.15700000e+00   1.74830000e+01
    8.99000000e+00   8.16600000e+00]
 [  1.50100000e+03  -8.50000000e-01   7.43500000e+00   1.74010000e+01
    8.68700000e+00   8.16300000e+00]
 [  1.50200000e+03  -1.05300000e+00   6.87200000e+00   1.79060000e+01
    9.07100000e+00   8.19400000e+00]
 [  1.50300000e+03  -2.13400000e+00   7.21000000e+00   1.83310000e+01
    8.92200000e+00   8.07700000e+00]]


In [26]:
!head -20 $filepath

European Seasonal Temperature Reconstructions
-----------------------------------------------------------------------
               World Data Center for Paleoclimatology, Boulder
                                  and
                     NOAA Paleoclimatology Program
-----------------------------------------------------------------------
NOTE: PLEASE CITE CONTRIBUTORS WHEN USING THIS DATA!!!!!


NAME OF DATA SET: European Seasonal Temperature Reconstructions
LAST UPDATE: 6/2006 (Original receipt by WDC Paleo)
CONTRIBUTOR: Juerg Luterbacher, University of Bern
IGBP PAGES/WDCA CONTRIBUTION SERIES NUMBER: 2006-060

SUGGESTED DATA CITATION: Luterbacher, J., et al.  2006. 
European Seasonal Temperature Reconstructions.
IGBP PAGES/World Data Center for Paleoclimatology 
Data Contribution Series # 2006-060.
NOAA/NCDC Paleoclimatology Program, Boulder CO, USA.



In [20]:
filepath

'../../data/europe-seasonal.txt'

In [32]:
print(data[5:10, 0:5])

[[  1.50500000e+03   4.80000000e-02   7.32300000e+00   1.73410000e+01
    9.28600000e+00]
 [  1.50600000e+03   6.40000000e-02   7.11600000e+00   1.75720000e+01
    8.95800000e+00]
 [  1.50700000e+03   6.12000000e-01   6.22900000e+00   1.75100000e+01
    9.07100000e+00]
 [  1.50800000e+03  -2.09900000e+00   6.81800000e+00   1.73100000e+01
    9.17800000e+00]
 [  1.50900000e+03  -1.44600000e+00   7.32300000e+00   1.78560000e+01
    9.07100000e+00]]


In [29]:
data.shape

(505, 6)

In [33]:
small = data[:5, 3:]
print('small is:')
print(small)

small is:
[[ 17.483   8.99    8.166]
 [ 17.401   8.687   8.163]
 [ 17.906   9.071   8.194]
 [ 18.331   8.922   8.077]
 [ 18.223   9.075   8.163]]


In [8]:
!head -120 $filepath | tail -2

Year        DJF         MAM        JJA         SON        Annual
1500      -0.945       7.157      17.483       8.990       8.166


In [13]:
print(data[0,:])

[  1.50000000e+03  -9.45000000e-01   7.15700000e+00   1.74830000e+01
   8.99000000e+00   8.16600000e+00]


[  1.50e+03  -9.45e-01   7.16e+00   1.75e+01   8.99e+00   8.17e+00]


In [8]:
#np.set_printoptions(precision=2)
#np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print(data[0,:])

[  1.50000000e+03  -9.45000000e-01   7.15700000e+00   1.74830000e+01
   8.99000000e+00   8.16600000e+00]


In [12]:
print(data[0:10,0])

[ 1500.  1501.  1502.  1503.  1504.  1505.  1506.  1507.  1508.  1509.]


In [11]:
data[0,0]

1500.0

In [13]:
data.dtype

dtype('float64')

In [16]:
data[0,0] = int(1500)

In [18]:
int(data[0,0])

1500

In [20]:
print(data[0,0])

1500.0
